export const ROUTES = {
    HOME: "#beranda",
    VIA_TOL: "#via-tol",
    AGENT: "#agen-resmi",
    CONTACT: "#kontak",
    LOUNGE: "#lounge",
    ATTACHMENT: "#lampiran",
    ABOUT: "#tentang-kami",
};

export const TIME_OPTIONS = [
    { value: "06:00", label: "06:00" },
    { value: "09:00", label: "09:00" },
    { value: "12:00", label: "12:00" },
    { value: "15:00", label: "15:00" },
    { value: "18:00", label: "18:00" },
    { value: "21:00", label: "21:00" },
];

export const ORIGIN_OPTIONS = [
    { value: "bandung", label: "Bandung" },
    { value: "banjar", label: "Banjar" },
    { value: "banjarnegara", label: "Banjarnegara" },
    { value: "banyumas", label: "Banyumas" },
    { value: "bototsari", label: "Bototsari" },
    { value: "boyolali", label: "Boyolali" },
    { value: "bumiayu", label: "Bumiayu" },
    { value: "buntu", label: "Buntu" },
    { value: "ciamis", label: "Ciamis" },
    { value: "cilacap", label: "Cilacap" },
    { value: "cirebon", label: "Cirebon" },
    { value: "jember", label: "Jember" },
    { value: "jombor", label: "Jombor" },
    { value: "kebumen", label: "Kebumen" },
    { value: "kediri", label: "Kediri" },
    { value: "klaten", label: "Klaten" },
    { value: "kudus", label: "Kudus" },
    { value: "magelang", label: "Magelang" },
    { value: "malang", label: "Malang" },
    { value: "pati", label: "Pati" },
    { value: "pekalongan", label: "Pekalongan" },
    { value: "pemalang", label: "Pemalang" },
    { value: "purwokerto", label: "Purwokerto" },
    { value: "purworejo", label: "Purworejo" },
    { value: "semarang", label: "Semarang" },
    { value: "solo", label: "Solo" },
    { value: "surabaya", label: "Surabaya" },
    { value: "tangerang", label: "Tangerang" },
    { value: "tuban", label: "Tuban" },
    { value: "tulungagung", label: "Tulungagung" },
    { value: "wonosobo", label: "Wonosobo" },
    { value: "yogyakarta", label: "Yogyakarta" },
    { value: "ngawi", label: "Ngawi" },
];

export const DESTINATION_OPTIONS = [
    { value: "bandung", label: "Bandung" },
    { value: "banjar", label: "Banjar" },
    { value: "banjarnegara", label: "Banjarnegara" },
    { value: "banyumas", label: "Banyumas" },
    { value: "bototsari", label: "Bototsari" },
    { value: "boyolali", label: "Boyolali" },
    { value: "bumiayu", label: "Bumiayu" },
    { value: "buntu", label: "Buntu" },
    { value: "ciamis", label: "Ciamis" },
    { value: "cilacap", label: "Cilacap" },
    { value: "cirebon", label: "Cirebon" },
    { value: "jember", label: "Jember" },
    { value: "jombor", label: "Jombor" },
    { value: "kebumen", label: "Kebumen" },
    { value: "kediri", label: "Kediri" },
    { value: "klaten", label: "Klaten" },
    { value: "kudus", label: "Kudus" },
    { value: "magelang", label: "Magelang" },
    { value: "malang", label: "Malang" },
    { value: "pati", label: "Pati" },
    { value: "pekalongan", label: "Pekalongan" },
    { value: "pemalang", label: "Pemalang" },
    { value: "purwokerto", label: "Purwokerto" },
    { value: "purworejo", label: "Purworejo" },
    { value: "semarang", label: "Semarang" },
    { value: "solo", label: "Solo" },
    { value: "surabaya", label: "Surabaya" },
    { value: "tangerang", label: "Tangerang" },
    { value: "tuban", label: "Tuban" },
    { value: "tulungagung", label: "Tulungagung" },
    { value: "wonosobo", label: "Wonosobo" },
    { value: "yogyakarta", label: "Yogyakarta" },
    { value: "ngawi", label: "Ngawi" },
];
